#include <iostream>
using namespace std;

int main() {
    int n;
    cin >> n;
    switch (n) {
        case 2:
            cout << "HAI" << endl;
            break;
        case 3:
            cout << "BA" << endl;
            break;
        case 4:
            cout << "TU" << endl;
            break;
        case 5:
            cout << "NAM" << endl;
            break;
        case 6:
            cout << "SAU" << endl;
            break;
        case 7:
            cout << "BAY" << endl;
            break;
        case 8:
            cout << "CHU NHAT" << endl;
            break;
        default:
            cout << "NO" << endl;
            break;
    }
}

